version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: bware_mysql
    ports:
      - 22022:22022
    environment:
      MYSQL_ROOT_PASSWORD: bwarewms
      MYSQL_TCP_PORT: 22022
      TZ: Asia/Seoul

    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]